#!/usr/bin/env python3
"""
kinect-bridge.py — Kinect v2 depth + body mask -> browser, over a local WebSocket.

Part of The Unlimiter suite. Feeds unlimiter-depth.js.

    pip install websockets numpy
    pip install pykinect2 comtypes        # only for real capture on Windows

    python kinect-bridge.py                  # real sensor
    python kinect-bridge.py --simulate       # synthetic figure, no hardware
    python kinect-bridge.py --scale 2        # halve resolution, quarter bandwidth

Then point the browser tool at  ws://localhost:8787

WHY A BRIDGE AT ALL
    The Kinect v2 is not a webcam. It speaks a proprietary USB 3.0 protocol and
    its depth stream is raw time-of-flight phase data that needs unwrapping
    before it means millimetres. No browser can do that directly, so something
    native has to read the sensor and hand over finished frames.

WHY RAW BINARY AND NOT VIDEO
    Depth must never go through a video codec. Chroma subsampling and DCT
    ringing wreck depth discontinuities exactly at the silhouette edges you
    care about. So this sends uncompressed 16-bit millimetres. At 512x424x30fps
    that is ~156 Mbit/s, which loopback does not even notice.

WIRE FORMAT  (one binary WebSocket message per frame)
    32-byte little-endian header, then payload:
      0  : 4  magic  b'ULD1'
      4  : 1  kind        1 = depth16 + bodyindex8
      5  : 1  flags       bit0 = already mirrored by the sender
      6  : 2  width       uint16
      8  : 2  height      uint16
      10 : 2  minDepthMm  uint16   sensor's usable near plane
      12 : 2  maxDepthMm  uint16   sensor's usable far plane
      14 : 2  (reserved)
      16 : 4  frameIndex  uint32
      20 : 4  (reserved)
      24 : 8  timestampMs float64
    payload = width*height*2 bytes depth  (uint16 LE, millimetres, 0 = no reading)
            + width*height   bytes body   (0..5 = player id, 255 = no body)

    On connect the server also sends one JSON text message describing the
    stream, so a client can size its buffers before the first binary frame.
"""

import argparse, asyncio, json, math, struct, sys, threading, time

try:
    import numpy as np
except ImportError:
    sys.exit("numpy is required:  pip install numpy")

# pykinect2 predates numpy 1.24, which removed np.int / np.float / np.bool.
# Put the aliases back before it is imported, or it dies on a name that has
# not existed for years.
# time.clock() went away in Python 3.8; pykinect2 still calls it for timing.
if not hasattr(time, "clock"):
    time.clock = time.perf_counter

import warnings as _w
with _w.catch_warnings():
    _w.simplefilter("ignore")
    for _n, _t in (("int", int), ("float", float), ("bool", bool), ("long", int)):
        try:
            getattr(np, _n)
        except Exception:
            try: setattr(np, _n, _t)
            except Exception: pass

try:
    import websockets
except ImportError:
    sys.exit("websockets is required:  pip install websockets")

MAGIC = b"ULD1"
KIND_DEPTH_BODY = 1
HEADER = 32

NO_BODY = 255


# --------------------------------------------------------------------------
# frame source: the real sensor
# --------------------------------------------------------------------------
def import_pykinect():
    """pykinect2 is a 2016 library. Import it with the failure modes named."""
    ver = "%d.%d" % (sys.version_info[0], sys.version_info[1])
    older = ("\n\nThis library is from 2016 and is only really happy on Python 3.8-3.10.\n"
             "You are on %s. If the errors above look like internals rather than\n"
             "anything you did, install Python 3.9 (64-bit) alongside what you have\n"
             "and run the bridge with that:\n"
             "    py -3.9 -m pip install pykinect2 comtypes numpy websockets\n"
             "    py -3.9 kinect-bridge.py" % ver)
    # pykinect2's PyKinectV2.py was generated by comtypes in 2016 and ends with
    # a _check_version() guard that rejects any newer comtypes codegen. The
    # guard is a version stamp, not a compatibility test, so stand it down.
    try:
        import comtypes
        if hasattr(comtypes, "_check_version"):
            comtypes._check_version = lambda *a, **k: None
    except Exception:
        pass
    try:
        from pykinect2 import PyKinectV2
        from pykinect2 import PyKinectRuntime
        return PyKinectV2, PyKinectRuntime
    except AssertionError as e:
        raise SystemExit(
            "pykinect2 failed an internal size assertion: %s\n\n"
            "Known 64-bit bug — a stale struct-size check, harmless to skip.\n"
            "Easiest fix, no file editing, just add -O to skip asserts:\n"
            "    python -O kinect-bridge.py\n\n"
            "Or edit the installed pykinect2/PyKinectV2.py, find\n"
            "    assert sizeof(tagSTATSTG) == 72, sizeof(tagSTATSTG)\n"
            "and change 72 to 80." % e + older)
    except ImportError as e:
        extra = ""
        if "version" in str(e).lower():
            extra = ("\n\nThat is comtypes refusing a module generated by an older\n"
                     "comtypes, not a problem with the sensor. If standing the version\n"
                     "guard down was not enough, pin the old one:\n"
                     "    pip install comtypes==1.1.7\n"
                     "and if it still complains, clear the generated cache:\n"
                     "    python -c \"import comtypes.client, shutil, os; "
                     "shutil.rmtree(os.path.join(os.path.dirname(comtypes.client.__file__),'gen'), ignore_errors=True)\"")
        raise SystemExit(
            "Could not import pykinect2: %s\n\n"
            "Needs the Kinect for Windows SDK 2.0 installed, then:\n"
            "    pip install pykinect2 comtypes\n"
            "Meanwhile --simulate proves the whole browser side without it."
            % e + extra + older)
    except Exception as e:
        raise SystemExit(
            "pykinect2 failed to load: %s: %s" % (type(e).__name__, e) + older)


class KinectSource:
    """Polls a Kinect v2 through pykinect2 / Kinect for Windows SDK 2.0."""

    def __init__(self):
        PyKinectV2, PyKinectRuntime = import_pykinect()

        if not hasattr(time, "clock"):
            time.clock = time.perf_counter
        flags = (PyKinectV2.FrameSourceTypes_Depth |
                 PyKinectV2.FrameSourceTypes_BodyIndex)
        self.rt = PyKinectRuntime.PyKinectRuntime(flags)

        # give the runtime a moment to bring the sensor up
        t0 = time.time()
        while self.rt.depth_frame_desc.Width == 0 and time.time() - t0 < 5:
            time.sleep(0.1)

        self.width = int(self.rt.depth_frame_desc.Width) or 512
        self.height = int(self.rt.depth_frame_desc.Height) or 424
        self.min_mm = 500
        self.max_mm = 4500
        self._depth = np.zeros(self.width * self.height, np.uint16)
        self._body = np.full(self.width * self.height, NO_BODY, np.uint8)
        print("Kinect v2 online: %dx%d" % (self.width, self.height))

    def read(self):
        """Returns (depth uint16[], body uint8[], got_new)."""
        got = False
        if self.rt.has_new_depth_frame():
            d = self.rt.get_last_depth_frame()
            if d is not None:
                self._depth = np.asarray(d, np.uint16).reshape(-1)
                got = True
        if self.rt.has_new_body_index_frame():
            b = self.rt.get_last_body_index_frame()
            if b is not None:
                self._body = np.asarray(b, np.uint8).reshape(-1)
                got = True
        return self._depth, self._body, got

    def close(self):
        try:
            self.rt.close()
        except Exception:
            pass


# --------------------------------------------------------------------------
# frame source: a synthetic figure, so the browser side can be proven first
# --------------------------------------------------------------------------
class SimSource:
    """A crude walking figure at a believable distance. No hardware needed."""

    def __init__(self, width=512, height=424):
        self.width, self.height = width, height
        self.min_mm, self.max_mm = 500, 4500
        self.t0 = time.time()
        yy, xx = np.mgrid[0:height, 0:width]
        self.xx = xx.astype(np.float32)
        self.yy = yy.astype(np.float32)
        # a back wall with a little tilt, so depth is never flat
        self.wall = (3600 + (self.xx - width / 2) * 0.35
                     + (self.yy - height / 2) * 0.15).astype(np.float32)

    def read(self):
        t = time.time() - self.t0
        w, h = self.width, self.height
        depth = self.wall.copy()
        body = np.full((h, w), NO_BODY, np.uint8)

        # figure drifts side to side and toward/away from the sensor
        cx = w * (0.5 + 0.26 * math.sin(t * 0.45))
        cz = 1900 + 620 * math.sin(t * 0.31)
        breathe = 1.0 + 0.04 * math.sin(t * 2.1)

        # head
        hx, hy, hr = cx, h * 0.26, w * 0.055 * breathe
        head = ((self.xx - hx) ** 2 + ((self.yy - hy) * 1.15) ** 2) < hr * hr
        # torso
        tx, ty = cx, h * 0.56
        tw, th = w * 0.085 * breathe, h * 0.20
        torso = (((self.xx - tx) / tw) ** 2 + ((self.yy - ty) / th) ** 2) < 1.0
        # arms swinging
        sw = math.sin(t * 1.7)
        figure = head | torso
        for side, phase in ((-1, sw), (1, -sw)):
            ax = cx + side * w * 0.085
            ay = h * 0.50
            for k in range(18):
                f = k / 17.0
                px = ax + side * f * w * 0.10 + f * phase * w * 0.07
                py = ay + f * h * 0.20 + f * abs(phase) * h * 0.03
                r = w * 0.022 * (1.0 - 0.3 * f)
                figure |= ((self.xx - px) ** 2 + (self.yy - py) ** 2) < r * r
        # legs
        for side in (-1, 1):
            lx = cx + side * w * 0.035
            for k in range(20):
                f = k / 19.0
                px = lx + side * f * w * 0.02 - side * sw * f * w * 0.05
                py = h * 0.74 + f * h * 0.24
                r = w * 0.026 * (1.0 - 0.25 * f)
                figure |= ((self.xx - px) ** 2 + (self.yy - py) ** 2) < r * r

        # round the body off in depth so it is not a flat cut-out
        rel = np.zeros_like(depth)
        rel[figure] = 1.0
        bulge = np.clip(1.0 - ((self.xx - cx) / (w * 0.13)) ** 2, 0, 1)
        depth[figure] = (cz - 120 * np.sqrt(bulge))[figure]
        body[figure] = 0

        # sensor noise and a few dropouts, because real depth is never clean
        depth += np.random.normal(0, 9, depth.shape).astype(np.float32)
        holes = np.random.random(depth.shape) < 0.004
        depth[holes] = 0

        d16 = np.clip(depth, 0, 65535).astype(np.uint16).reshape(-1)
        return d16, body.reshape(-1), True

    def close(self):
        pass


# --------------------------------------------------------------------------
# shared latest-frame slot: capture thread writes, sender loop reads
# --------------------------------------------------------------------------
class FrameSlot:
    def __init__(self):
        self.lock = threading.Lock()
        self.payload = None
        self.index = 0
        self.stamp = 0.0

    def put(self, payload, stamp):
        with self.lock:
            self.payload = payload
            self.index += 1
            self.stamp = stamp

    def get(self):
        with self.lock:
            return self.payload, self.index, self.stamp


def downscale(depth, body, w, h, factor):
    """Nearest-neighbour decimation. Never average depth — averaging across an
    edge invents a surface halfway between the subject and the wall."""
    if factor <= 1:
        return depth, body, w, h
    nw, nh = w // factor, h // factor
    d = depth.reshape(h, w)[::factor, ::factor][:nh, :nw]
    b = body.reshape(h, w)[::factor, ::factor][:nh, :nw]
    return d.reshape(-1).copy(), b.reshape(-1).copy(), nw, nh


def capture_loop(src, slot, stop, fps, scale, mirror):
    period = 1.0 / max(1.0, fps)
    nxt = time.time()
    last_good = time.time()
    dry = False
    got_total = 0
    while not stop.is_set():
        depth, body, got = src.read()
        now = time.time()
        # watchdog: the sensor dropping out looks identical to a quiet scene
        # from up here, so say so rather than silently repeating a stale frame
        if got:
            got_total += 1
            if dry:
                print("  sensor back after %.1fs" % (now - last_good))
                dry = False
            last_good = now
        elif not dry and now - last_good > 1.5:
            dry = True
            print("  !! no frames from the sensor for %.1fs — it is dropping out, "
                  "not the network" % (now - last_good))
        if got:
            w, h = src.width, src.height
            if mirror:
                depth = depth.reshape(h, w)[:, ::-1].reshape(-1).copy()
                body = body.reshape(h, w)[:, ::-1].reshape(-1).copy()
            depth, body, w, h = downscale(depth, body, w, h, scale)
            head = struct.pack(
                "<4sBBHHHHHII d",
                MAGIC, KIND_DEPTH_BODY, 1 if mirror else 0,
                w, h, src.min_mm, src.max_mm, 0,
                got_total & 0xFFFFFFFF, 0, time.time() * 1000.0)
            slot.put(head + depth.tobytes() + body.tobytes(), now)
        rest = nxt + period - time.time()
        if rest > 0:
            time.sleep(rest)
        nxt = max(nxt + period, time.time() - period)


# --------------------------------------------------------------------------
async def main():
    ap = argparse.ArgumentParser(description="Kinect v2 -> browser depth bridge")
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=8787)
    ap.add_argument("--fps", type=float, default=30.0)
    ap.add_argument("--scale", type=int, default=1,
                    help="integer decimation: 2 sends quarter the pixels")
    ap.add_argument("--simulate", action="store_true",
                    help="synthetic figure, no sensor required")
    ap.add_argument("--no-mirror", action="store_true",
                    help="send unmirrored; default mirrors so it reads like a mirror")
    ap.add_argument("--selftest", action="store_true",
                    help="report the environment and try the sensor, then exit")
    args = ap.parse_args()

    if args.selftest:
        print("python    : %s" % sys.version.replace("\n", " "))
        print("executable: %s" % sys.executable)
        print("numpy     : %s" % np.__version__)
        print("websockets: %s" % getattr(websockets, "__version__", "?"))
        print("asserts   : %s" % ("on — add -O to skip them" if __debug__ else "off (-O)"))
        try:
            import comtypes
            print("comtypes  : %s" % getattr(comtypes, "__version__", "present"))
        except Exception as e:
            print("comtypes  : MISSING (%s)" % e)
        print("-- trying the sensor --")
        src = KinectSource()
        import time as _t
        t0 = _t.time()
        nd = nb = 0
        best_d = best_b = 0
        raw_note = ""
        while _t.time() - t0 < 5.0:
            if src.rt.has_new_depth_frame():
                d = src.rt.get_last_depth_frame()
                if d is not None:
                    nd += 1
                    if not raw_note:
                        raw_note = "depth frame: dtype=%s size=%s" % (
                            getattr(d, "dtype", "?"), getattr(d, "size", len(d)))
                    a = np.asarray(d).reshape(-1)
                    best_d = max(best_d, int((a > 0).sum()))
            if src.rt.has_new_body_index_frame():
                b = src.rt.get_last_body_index_frame()
                if b is not None:
                    nb += 1
                    a = np.asarray(b).reshape(-1)
                    best_b = max(best_b, int((a != NO_BODY).sum()))
            _t.sleep(0.005)
        secs = _t.time() - t0
        if raw_note:
            print(raw_note)
        print("depth frames : %d in %.1fs (%.1f fps), best frame had %d px with a reading"
              % (nd, secs, nd / secs, best_d))
        print("body frames  : %d in %.1fs, best frame flagged %d px as a person"
              % (nb, secs, best_b))
        if nd == 0:
            print("\nNo depth frames arrived at all.\n"
                  "  * Close Kinect Studio. It holds the sensor and other apps get nothing.\n"
                  "  * Check the Kinect Monitor service is running (services.msc).\n"
                  "  * Unplug and replug the adapter, then try again.")
        elif best_d == 0:
            print("\nFrames are arriving but every pixel reads zero — the sensor is\n"
                  "streaming but not ranging. Usually means it is still warming up,\n"
                  "or something opaque is right against the lens.")
        else:
            print("\nLooks alive.")
        src.close()
        return

    src = SimSource() if args.simulate else KinectSource()
    mirror = not args.no_mirror
    sw = src.width // max(1, args.scale)
    sh = src.height // max(1, args.scale)

    hello = json.dumps({
        "protocol": "ULD1", "kind": KIND_DEPTH_BODY,
        "width": sw, "height": sh,
        "minDepthMm": src.min_mm, "maxDepthMm": src.max_mm,
        "fps": args.fps, "mirrored": mirror,
        "source": "simulate" if args.simulate else "kinect-v2",
    })

    slot = FrameSlot()
    stop = threading.Event()
    th = threading.Thread(target=capture_loop,
                          args=(src, slot, stop, args.fps, args.scale, mirror),
                          daemon=True)
    th.start()

    clients = set()

    async def serve(ws):
        clients.add(ws)
        peer = getattr(ws, "remote_address", ("?",))[0]
        print("client connected (%s) — %d total" % (peer, len(clients)))
        sent = skipped = 0
        t0 = time.time()
        try:
            await ws.send(hello)
            last = -1
            period = 1.0 / max(1.0, args.fps)
            while True:
                payload, idx, _ = slot.get()
                if payload is not None and idx != last:
                    # if the browser is behind, drop this frame rather than
                    # queue it: stale depth is worse than no depth, and a
                    # growing write buffer is what stalls the connection
                    buffered = 0
                    tr = getattr(ws, "transport", None)
                    if tr is not None:
                        try: buffered = tr.get_write_buffer_size()
                        except Exception: buffered = 0
                    last = idx
                    if buffered > len(payload) * 2:
                        skipped += 1
                    else:
                        await ws.send(payload)
                        sent += 1
                    if (sent + skipped) % 150 == 0:
                        el = time.time() - t0
                        print("  %d sent, %d dropped (%.1f fps out)"
                              % (sent, skipped, sent / el if el else 0))
                await asyncio.sleep(period * 0.5)
        except Exception as e:
            # never swallow this: it is the only clue when a link keeps dying
            print("client dropped: %s: %s" % (type(e).__name__, e))
        finally:
            clients.discard(ws)
            print("client gone after %d frames — %d left" % (sent, len(clients)))

    bytes_per = HEADER + sw * sh * 3
    print("serving ws://%s:%d   %dx%d  %.0f fps  %.1f MB/s  (%s)"
          % (args.host, args.port, sw, sh, args.fps,
             bytes_per * args.fps / 1e6,
             "simulated" if args.simulate else "Kinect v2"))
    print("Ctrl-C to stop.")

    try:
        async with websockets.serve(serve, args.host, args.port,
                                    max_size=None, compression=None):
            await asyncio.Future()
    finally:
        stop.set()
        src.close()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nstopped.")
